{
  "patcher": {
    "fileversion": 1,
    "appversion": { "major": 9, "minor": 1, "revision": 5, "architecture": "x64", "modernui": 1 },
    "classnamespace": "box",
    "rect": [ 60.0, 60.0, 1440.0, 900.0 ],
    "boxes": [
      { "box": { "id": "title", "maxclass": "comment", "text": "MLR per-group channel strip — exact-dry filter, clean/OctiMax compressor A/B, parallel mix, saturation and trim", "patching_rect": [ 25.0, 15.0, 750.0, 22.0 ] } },
      { "box": { "id": "in-l", "maxclass": "inlet", "index": 1, "numinlets": 0, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 25.0, 60.0, 30.0, 30.0 ] } },
      { "box": { "id": "in-r", "maxclass": "inlet", "index": 2, "numinlets": 0, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 80.0, 60.0, 30.0, 30.0 ] } },

      { "box": { "id": "r-cutoff", "maxclass": "newobj", "text": "r #1[channelstrip]cutoff", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 180.0, 55.0, 146.0, 22.0 ] } },
      { "box": { "id": "load-cutoff", "maxclass": "newobj", "text": "loadmess 1.", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 335.0, 55.0, 75.0, 22.0 ] } },
      { "box": { "id": "clip-cutoff", "maxclass": "newobj", "text": "clip 0. 1.", "numinlets": 3, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 180.0, 90.0, 66.0, 22.0 ] } },
      { "box": { "id": "trigger-cutoff", "maxclass": "newobj", "text": "t f f", "numinlets": 1, "numoutlets": 2, "outlettype": [ "float", "float" ], "patching_rect": [ 180.0, 125.0, 38.0, 22.0 ] } },
      { "box": { "id": "pack-cutoff", "maxclass": "newobj", "text": "pack 0. 20", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 180.0, 160.0, 72.0, 22.0 ] } },
      { "box": { "id": "line-cutoff", "maxclass": "newobj", "text": "line~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 180.0, 195.0, 42.0, 22.0 ] } },

      { "box": { "id": "r-filtermod", "maxclass": "newobj", "text": "r #1[filterfx]level", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 275.0, 90.0, 112.0, 22.0 ] } },
      { "box": { "id": "load-filtermod", "maxclass": "newobj", "text": "loadmess 1. 0", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 395.0, 90.0, 93.0, 22.0 ] } },
      { "box": { "id": "unpack-filtermod", "maxclass": "newobj", "text": "unpack 0. 8.", "numinlets": 1, "numoutlets": 2, "outlettype": [ "float", "float" ], "patching_rect": [ 275.0, 125.0, 82.0, 22.0 ] } },
      { "box": { "id": "pack-filtermod", "maxclass": "newobj", "text": "pack 0. 8.", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 275.0, 160.0, 75.0, 22.0 ] } },
      { "box": { "id": "line-filtermod", "maxclass": "newobj", "text": "line~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 275.0, 195.0, 42.0, 22.0 ] } },

      { "box": { "id": "r-resonance", "maxclass": "newobj", "text": "r #1[channelstrip]resonance", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 510.0, 55.0, 164.0, 22.0 ] } },
      { "box": { "id": "load-resonance", "maxclass": "newobj", "text": "loadmess 0.", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 685.0, 55.0, 75.0, 22.0 ] } },
      { "box": { "id": "clip-resonance", "maxclass": "newobj", "text": "clip 0. 1.", "numinlets": 3, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 510.0, 90.0, 66.0, 22.0 ] } },
      { "box": { "id": "trigger-resonance", "maxclass": "newobj", "text": "t f f", "numinlets": 1, "numoutlets": 2, "outlettype": [ "float", "float" ], "patching_rect": [ 510.0, 125.0, 38.0, 22.0 ] } },
      { "box": { "id": "pack-resonance", "maxclass": "newobj", "text": "pack 0. 20", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 510.0, 160.0, 72.0, 22.0 ] } },
      { "box": { "id": "line-resonance", "maxclass": "newobj", "text": "line~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 510.0, 195.0, 42.0, 22.0 ] } },

      { "box": { "id": "filter", "maxclass": "newobj", "text": "mlr_filter", "numinlets": 5, "numoutlets": 2, "outlettype": [ "signal", "signal" ], "patching_rect": [ 25.0, 250.0, 92.0, 22.0 ] } },
      { "box": { "id": "clean-comp", "maxclass": "newobj", "text": "mlr_compressor", "numinlets": 7, "numoutlets": 3, "outlettype": [ "signal", "signal", "signal" ], "patching_rect": [ 25.0, 335.0, 112.0, 22.0 ] } },
      { "box": { "id": "omx-comp", "maxclass": "newobj", "text": "omx.comp~", "numinlets": 2, "numoutlets": 3, "outlettype": [ "signal", "signal", "" ], "patching_rect": [ 165.0, 335.0, 76.0, 22.0 ] } },
      { "box": { "id": "omx-loadbang", "maxclass": "newobj", "text": "loadbang", "numinlets": 1, "numoutlets": 1, "outlettype": [ "bang" ], "patching_rect": [ 255.0, 300.0, 60.0, 22.0 ] } },
      { "box": { "id": "omx-init", "maxclass": "message", "text": "agcEnabled 1, limEnabled 0, ngEnabled 0, dualBandEnabled 0, channelCoupling 0, range 0, meters 0, bypass 0", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 255.0, 335.0, 575.0, 22.0 ] } },

      { "box": { "id": "r-engine", "maxclass": "newobj", "text": "r #1[channelstrip]engine", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 810.0, 55.0, 148.0, 22.0 ] } },
      { "box": { "id": "load-engine", "maxclass": "newobj", "text": "loadmess 0", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 970.0, 55.0, 72.0, 22.0 ] } },
      { "box": { "id": "clip-engine", "maxclass": "newobj", "text": "clip 0 2", "numinlets": 3, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 810.0, 90.0, 56.0, 22.0 ] } },
      { "box": { "id": "trigger-engine", "maxclass": "newobj", "text": "t i i", "numinlets": 1, "numoutlets": 2, "outlettype": [ "int", "int" ], "patching_rect": [ 810.0, 125.0, 38.0, 22.0 ] } },
      { "box": { "id": "r-mix", "maxclass": "newobj", "text": "r #1[channelstrip]mix", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 1060.0, 55.0, 132.0, 22.0 ] } },
      { "box": { "id": "load-mix", "maxclass": "newobj", "text": "loadmess 1.", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 1200.0, 55.0, 75.0, 22.0 ] } },
      { "box": { "id": "clip-mix", "maxclass": "newobj", "text": "clip 0. 1.", "numinlets": 3, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 1060.0, 90.0, 66.0, 22.0 ] } },
      { "box": { "id": "trigger-mix", "maxclass": "newobj", "text": "t f f", "numinlets": 1, "numoutlets": 2, "outlettype": [ "float", "float" ], "patching_rect": [ 1060.0, 125.0, 38.0, 22.0 ] } },
      { "box": { "id": "engine-mix", "maxclass": "newobj", "text": "pak 0 1.", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 900.0, 165.0, 66.0, 22.0 ] } },
      { "box": { "id": "expr-dry", "maxclass": "newobj", "text": "expr 1. - $f2 * ($i1 != 0)", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 810.0, 205.0, 184.0, 22.0 ] } },
      { "box": { "id": "expr-clean", "maxclass": "newobj", "text": "expr $f2 * ($i1 == 1)", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 1010.0, 205.0, 170.0, 22.0 ] } },
      { "box": { "id": "expr-omx", "maxclass": "newobj", "text": "expr $f2 * ($i1 == 2)", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 1195.0, 205.0, 170.0, 22.0 ] } },
      { "box": { "id": "pack-dry", "maxclass": "newobj", "text": "pack 0. 20", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 845.0, 240.0, 72.0, 22.0 ] } },
      { "box": { "id": "pack-clean-weight", "maxclass": "newobj", "text": "pack 0. 20", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 1050.0, 240.0, 72.0, 22.0 ] } },
      { "box": { "id": "pack-omx-weight", "maxclass": "newobj", "text": "pack 0. 20", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 1235.0, 240.0, 72.0, 22.0 ] } },
      { "box": { "id": "line-dry", "maxclass": "newobj", "text": "line~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 845.0, 275.0, 42.0, 22.0 ] } },
      { "box": { "id": "line-clean-weight", "maxclass": "newobj", "text": "line~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 1050.0, 275.0, 42.0, 22.0 ] } },
      { "box": { "id": "line-omx-weight", "maxclass": "newobj", "text": "line~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 1235.0, 275.0, 42.0, 22.0 ] } },

      { "box": { "id": "r-threshold", "maxclass": "newobj", "text": "r #1[channelstrip]threshold", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 450.0, 300.0, 162.0, 22.0 ] } },
      { "box": { "id": "load-threshold", "maxclass": "newobj", "text": "loadmess -18.", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 620.0, 300.0, 90.0, 22.0 ] } },
      { "box": { "id": "clip-threshold", "maxclass": "newobj", "text": "clip -60. 0.", "numinlets": 3, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 450.0, 335.0, 78.0, 22.0 ] } },
      { "box": { "id": "trigger-threshold", "maxclass": "newobj", "text": "t f f f", "numinlets": 1, "numoutlets": 3, "outlettype": [ "float", "float", "float" ], "patching_rect": [ 450.0, 370.0, 52.0, 22.0 ] } },
      { "box": { "id": "abs-threshold", "maxclass": "newobj", "text": "abs 0.", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 535.0, 405.0, 48.0, 22.0 ] } },
      { "box": { "id": "pre-omx-threshold", "maxclass": "newobj", "text": "prepend agcThreshold", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 535.0, 440.0, 134.0, 22.0 ] } },

      { "box": { "id": "r-ratio", "maxclass": "newobj", "text": "r #1[channelstrip]ratio", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 700.0, 300.0, 137.0, 22.0 ] } },
      { "box": { "id": "load-ratio", "maxclass": "newobj", "text": "loadmess 4.", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 845.0, 300.0, 75.0, 22.0 ] } },
      { "box": { "id": "clip-ratio", "maxclass": "newobj", "text": "clip 1. 20.", "numinlets": 3, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 700.0, 335.0, 72.0, 22.0 ] } },
      { "box": { "id": "trigger-ratio", "maxclass": "newobj", "text": "t f f f", "numinlets": 1, "numoutlets": 3, "outlettype": [ "float", "float", "float" ], "patching_rect": [ 700.0, 370.0, 52.0, 22.0 ] } },
      { "box": { "id": "int-ratio", "maxclass": "newobj", "text": "i", "numinlets": 2, "numoutlets": 1, "outlettype": [ "int" ], "patching_rect": [ 785.0, 405.0, 30.0, 22.0 ] } },
      { "box": { "id": "pre-omx-ratio", "maxclass": "newobj", "text": "prepend ratio", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 785.0, 440.0, 88.0, 22.0 ] } },

      { "box": { "id": "r-attack", "maxclass": "newobj", "text": "r #1[channelstrip]attack", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 925.0, 335.0, 142.0, 22.0 ] } },
      { "box": { "id": "load-attack", "maxclass": "newobj", "text": "loadmess 10.", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 1075.0, 335.0, 82.0, 22.0 ] } },
      { "box": { "id": "clip-attack", "maxclass": "newobj", "text": "clip 0.1 500.", "numinlets": 3, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 925.0, 370.0, 86.0, 22.0 ] } },
      { "box": { "id": "trigger-attack", "maxclass": "newobj", "text": "t f f f", "numinlets": 1, "numoutlets": 3, "outlettype": [ "float", "float", "float" ], "patching_rect": [ 925.0, 405.0, 52.0, 22.0 ] } },
      { "box": { "id": "map-omx-attack", "maxclass": "newobj", "text": "expr 150. * (1. - log(max($f1\\, 0.1) / 0.1) / log(5000.))", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 1010.0, 440.0, 320.0, 22.0 ] } },
      { "box": { "id": "pre-omx-attack", "maxclass": "newobj", "text": "prepend attack", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 1235.0, 475.0, 92.0, 22.0 ] } },

      { "box": { "id": "r-release", "maxclass": "newobj", "text": "r #1[channelstrip]release", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 925.0, 510.0, 146.0, 22.0 ] } },
      { "box": { "id": "load-release", "maxclass": "newobj", "text": "loadmess 120.", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 1080.0, 510.0, 90.0, 22.0 ] } },
      { "box": { "id": "clip-release", "maxclass": "newobj", "text": "clip 5. 5000.", "numinlets": 3, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 925.0, 545.0, 86.0, 22.0 ] } },
      { "box": { "id": "trigger-release", "maxclass": "newobj", "text": "t f f f", "numinlets": 1, "numoutlets": 3, "outlettype": [ "float", "float", "float" ], "patching_rect": [ 925.0, 580.0, 52.0, 22.0 ] } },
      { "box": { "id": "map-omx-release", "maxclass": "newobj", "text": "expr 150. * (1. - log(max($f1\\, 5.) / 5.) / log(1000.))", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 1010.0, 615.0, 310.0, 22.0 ] } },
      { "box": { "id": "pre-omx-release", "maxclass": "newobj", "text": "prepend release", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 1235.0, 650.0, 96.0, 22.0 ] } },

      { "box": { "id": "r-knee", "maxclass": "newobj", "text": "r #1[channelstrip]knee", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 700.0, 510.0, 136.0, 22.0 ] } },
      { "box": { "id": "load-knee", "maxclass": "newobj", "text": "loadmess 6.", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 845.0, 510.0, 75.0, 22.0 ] } },
      { "box": { "id": "clip-knee", "maxclass": "newobj", "text": "clip 0. 24.", "numinlets": 3, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 700.0, 545.0, 72.0, 22.0 ] } },
      { "box": { "id": "trigger-knee", "maxclass": "newobj", "text": "t f f", "numinlets": 1, "numoutlets": 2, "outlettype": [ "float", "float" ], "patching_rect": [ 700.0, 580.0, 38.0, 22.0 ] } },

      { "box": { "id": "r-makeup", "maxclass": "newobj", "text": "r #1[channelstrip]makeup", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 450.0, 510.0, 146.0, 22.0 ] } },
      { "box": { "id": "load-makeup", "maxclass": "newobj", "text": "loadmess 0.", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 605.0, 510.0, 75.0, 22.0 ] } },
      { "box": { "id": "clip-makeup", "maxclass": "newobj", "text": "clip -12. 24.", "numinlets": 3, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 450.0, 545.0, 84.0, 22.0 ] } },
      { "box": { "id": "trigger-makeup", "maxclass": "newobj", "text": "t f f f", "numinlets": 1, "numoutlets": 3, "outlettype": [ "float", "float", "float" ], "patching_rect": [ 450.0, 580.0, 52.0, 22.0 ] } },
      { "box": { "id": "makeup-scalar", "maxclass": "newobj", "text": "expr pow(10\\, $f1 / 20.)", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 520.0, 615.0, 145.0, 22.0 ] } },
      { "box": { "id": "pack-makeup", "maxclass": "newobj", "text": "pack 1. 20", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 520.0, 650.0, 72.0, 22.0 ] } },
      { "box": { "id": "line-makeup", "maxclass": "newobj", "text": "line~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 520.0, 685.0, 42.0, 22.0 ] } },

      { "box": { "id": "dry-l", "maxclass": "newobj", "text": "*~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 25.0, 510.0, 32.0, 22.0 ] } },
      { "box": { "id": "dry-r", "maxclass": "newobj", "text": "*~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 75.0, 510.0, 32.0, 22.0 ] } },
      { "box": { "id": "clean-makeup-l", "maxclass": "newobj", "text": "*~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 25.0, 405.0, 32.0, 22.0 ] } },
      { "box": { "id": "clean-makeup-r", "maxclass": "newobj", "text": "*~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 75.0, 405.0, 32.0, 22.0 ] } },
      { "box": { "id": "clean-weight-l", "maxclass": "newobj", "text": "*~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 25.0, 450.0, 32.0, 22.0 ] } },
      { "box": { "id": "clean-weight-r", "maxclass": "newobj", "text": "*~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 75.0, 450.0, 32.0, 22.0 ] } },
      { "box": { "id": "omx-makeup-l", "maxclass": "newobj", "text": "*~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 165.0, 405.0, 32.0, 22.0 ] } },
      { "box": { "id": "omx-makeup-r", "maxclass": "newobj", "text": "*~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 215.0, 405.0, 32.0, 22.0 ] } },
      { "box": { "id": "omx-weight-l", "maxclass": "newobj", "text": "*~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 165.0, 450.0, 32.0, 22.0 ] } },
      { "box": { "id": "omx-weight-r", "maxclass": "newobj", "text": "*~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 215.0, 450.0, 32.0, 22.0 ] } },
      { "box": { "id": "sum-a-l", "maxclass": "newobj", "text": "+~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 25.0, 555.0, 32.0, 22.0 ] } },
      { "box": { "id": "sum-a-r", "maxclass": "newobj", "text": "+~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 75.0, 555.0, 32.0, 22.0 ] } },
      { "box": { "id": "sum-b-l", "maxclass": "newobj", "text": "+~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 25.0, 600.0, 32.0, 22.0 ] } },
      { "box": { "id": "sum-b-r", "maxclass": "newobj", "text": "+~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 75.0, 600.0, 32.0, 22.0 ] } },

      { "box": { "id": "r-drive", "maxclass": "newobj", "text": "r #1[channelstrip]drive", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 180.0, 600.0, 140.0, 22.0 ] } },
      { "box": { "id": "load-drive", "maxclass": "newobj", "text": "loadmess 0.", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 330.0, 600.0, 75.0, 22.0 ] } },
      { "box": { "id": "clip-drive", "maxclass": "newobj", "text": "clip 0. 12.", "numinlets": 3, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 180.0, 635.0, 72.0, 22.0 ] } },
      { "box": { "id": "trigger-drive", "maxclass": "newobj", "text": "t f f", "numinlets": 1, "numoutlets": 2, "outlettype": [ "float", "float" ], "patching_rect": [ 180.0, 670.0, 38.0, 22.0 ] } },
      { "box": { "id": "saturator", "maxclass": "newobj", "text": "mlr_saturator", "numinlets": 3, "numoutlets": 2, "outlettype": [ "signal", "signal" ], "patching_rect": [ 25.0, 700.0, 100.0, 22.0 ] } },

      { "box": { "id": "r-trim", "maxclass": "newobj", "text": "r #1[channelstrip]trim", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 180.0, 725.0, 132.0, 22.0 ] } },
      { "box": { "id": "load-trim", "maxclass": "newobj", "text": "loadmess 0.", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 320.0, 725.0, 75.0, 22.0 ] } },
      { "box": { "id": "clip-trim", "maxclass": "newobj", "text": "clip -24. 12.", "numinlets": 3, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 180.0, 760.0, 84.0, 22.0 ] } },
      { "box": { "id": "trigger-trim", "maxclass": "newobj", "text": "t f f", "numinlets": 1, "numoutlets": 2, "outlettype": [ "float", "float" ], "patching_rect": [ 180.0, 795.0, 38.0, 22.0 ] } },
      { "box": { "id": "trim-scalar", "maxclass": "newobj", "text": "expr pow(10\\, $f1 / 20.)", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 230.0, 830.0, 145.0, 22.0 ] } },
      { "box": { "id": "pack-trim", "maxclass": "newobj", "text": "pack 1. 20", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 390.0, 830.0, 72.0, 22.0 ] } },
      { "box": { "id": "line-trim", "maxclass": "newobj", "text": "line~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 475.0, 830.0, 42.0, 22.0 ] } },
      { "box": { "id": "trim-l", "maxclass": "newobj", "text": "*~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 25.0, 770.0, 32.0, 22.0 ] } },
      { "box": { "id": "trim-r", "maxclass": "newobj", "text": "*~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 75.0, 770.0, 32.0, 22.0 ] } },
      { "box": { "id": "out-l", "maxclass": "outlet", "index": 1, "numinlets": 1, "numoutlets": 0, "patching_rect": [ 25.0, 835.0, 30.0, 30.0 ] } },
      { "box": { "id": "out-r", "maxclass": "outlet", "index": 2, "numinlets": 1, "numoutlets": 0, "patching_rect": [ 75.0, 835.0, 30.0, 30.0 ] } },

      { "box": { "id": "state-channel-load", "maxclass": "newobj", "text": "loadmess #1", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 570.0, 725.0, 80.0, 22.0 ] } },
      { "box": { "id": "state-channel-index", "maxclass": "newobj", "text": "- 1", "numinlets": 2, "numoutlets": 1, "outlettype": [ "int" ], "patching_rect": [ 570.0, 760.0, 32.0, 22.0 ] } },
      { "box": { "id": "state-pak", "maxclass": "newobj", "text": "pak i i f f f f f f f f f f f f", "numinlets": 14, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 620.0, 795.0, 300.0, 22.0 ] } },
      { "box": { "id": "state-speedlim", "maxclass": "newobj", "text": "speedlim 33", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 935.0, 795.0, 74.0, 22.0 ] } },
      { "box": { "id": "state-prepend", "maxclass": "newobj", "text": "prepend channel_strip", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 1025.0, 795.0, 137.0, 22.0 ] } },
      { "box": { "id": "hud-state-send", "maxclass": "newobj", "text": "s mlr_hud_state", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 1175.0, 795.0, 104.0, 22.0 ] } },
      { "box": { "id": "r-snapshot", "maxclass": "newobj", "text": "r channel_strip_snapshot", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 620.0, 725.0, 148.0, 22.0 ] } },
      { "box": { "id": "snapshot-channel", "maxclass": "message", "text": "#1", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 680.0, 760.0, 32.0, 22.0 ] } },

      { "box": { "id": "input-abs-l", "maxclass": "newobj", "text": "abs~", "numinlets": 1, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 620.0, 520.0, 40.0, 22.0 ] } },
      { "box": { "id": "input-abs-r", "maxclass": "newobj", "text": "abs~", "numinlets": 1, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 670.0, 520.0, 40.0, 22.0 ] } },
      { "box": { "id": "input-max", "maxclass": "newobj", "text": "maximum~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 620.0, 555.0, 70.0, 22.0 ] } },
      { "box": { "id": "input-peak", "maxclass": "newobj", "text": "peakamp~ 0", "numinlets": 1, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 620.0, 590.0, 76.0, 22.0 ] } },
      { "box": { "id": "input-db", "maxclass": "newobj", "text": "expr 20. * log10(max($f1\\, 0.000001))", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 620.0, 625.0, 210.0, 22.0 ] } },
      { "box": { "id": "output-abs-l", "maxclass": "newobj", "text": "abs~", "numinlets": 1, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 850.0, 520.0, 40.0, 22.0 ] } },
      { "box": { "id": "output-abs-r", "maxclass": "newobj", "text": "abs~", "numinlets": 1, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 900.0, 520.0, 40.0, 22.0 ] } },
      { "box": { "id": "output-max", "maxclass": "newobj", "text": "maximum~", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 850.0, 555.0, 70.0, 22.0 ] } },
      { "box": { "id": "output-peak", "maxclass": "newobj", "text": "peakamp~ 0", "numinlets": 1, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 850.0, 590.0, 76.0, 22.0 ] } },
      { "box": { "id": "output-db", "maxclass": "newobj", "text": "expr 20. * log10(max($f1\\, 0.000001))", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 850.0, 625.0, 210.0, 22.0 ] } },
      { "box": { "id": "r-meter-selected", "maxclass": "newobj", "text": "r channel_strip_selected", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 1080.0, 520.0, 148.0, 22.0 ] } },
      { "box": { "id": "meter-equals", "maxclass": "newobj", "text": "== #1", "numinlets": 2, "numoutlets": 1, "outlettype": [ "int" ], "patching_rect": [ 1080.0, 555.0, 48.0, 22.0 ] } },
      { "box": { "id": "meter-metro", "maxclass": "newobj", "text": "metro 100", "numinlets": 2, "numoutlets": 1, "outlettype": [ "bang" ], "patching_rect": [ 1080.0, 590.0, 68.0, 22.0 ] } },
      { "box": { "id": "meter-trigger", "maxclass": "newobj", "text": "t b b", "numinlets": 1, "numoutlets": 2, "outlettype": [ "bang", "bang" ], "patching_rect": [ 1080.0, 625.0, 42.0, 22.0 ] } },
      { "box": { "id": "meter-pak", "maxclass": "newobj", "text": "pak i f f f", "numinlets": 4, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 620.0, 675.0, 90.0, 22.0 ] } },
      { "box": { "id": "meter-speedlim", "maxclass": "newobj", "text": "speedlim 90", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 725.0, 675.0, 74.0, 22.0 ] } },
      { "box": { "id": "meter-prepend", "maxclass": "newobj", "text": "prepend channel_strip_meter", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 815.0, 675.0, 170.0, 22.0 ] } },
      { "box": { "id": "meter-send", "maxclass": "newobj", "text": "s mlr_hud_state", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 1000.0, 675.0, 104.0, 22.0 ] } }
    ],
    "lines": [
      { "patchline": { "source": [ "in-l", 0 ], "destination": [ "filter", 0 ] } },
      { "patchline": { "source": [ "in-r", 0 ], "destination": [ "filter", 1 ] } },
      { "patchline": { "source": [ "r-cutoff", 0 ], "destination": [ "clip-cutoff", 0 ] } },
      { "patchline": { "source": [ "load-cutoff", 0 ], "destination": [ "clip-cutoff", 0 ] } },
      { "patchline": { "source": [ "clip-cutoff", 0 ], "destination": [ "trigger-cutoff", 0 ] } },
      { "patchline": { "source": [ "trigger-cutoff", 0 ], "destination": [ "pack-cutoff", 0 ] } },
      { "patchline": { "source": [ "pack-cutoff", 0 ], "destination": [ "line-cutoff", 0 ] } },
      { "patchline": { "source": [ "line-cutoff", 0 ], "destination": [ "filter", 2 ] } },
      { "patchline": { "source": [ "r-filtermod", 0 ], "destination": [ "unpack-filtermod", 0 ] } },
      { "patchline": { "source": [ "load-filtermod", 0 ], "destination": [ "unpack-filtermod", 0 ] } },
      { "patchline": { "source": [ "unpack-filtermod", 1 ], "destination": [ "pack-filtermod", 1 ] } },
      { "patchline": { "source": [ "unpack-filtermod", 0 ], "destination": [ "pack-filtermod", 0 ] } },
      { "patchline": { "source": [ "pack-filtermod", 0 ], "destination": [ "line-filtermod", 0 ] } },
      { "patchline": { "source": [ "line-filtermod", 0 ], "destination": [ "filter", 3 ] } },
      { "patchline": { "source": [ "r-resonance", 0 ], "destination": [ "clip-resonance", 0 ] } },
      { "patchline": { "source": [ "load-resonance", 0 ], "destination": [ "clip-resonance", 0 ] } },
      { "patchline": { "source": [ "clip-resonance", 0 ], "destination": [ "trigger-resonance", 0 ] } },
      { "patchline": { "source": [ "trigger-resonance", 0 ], "destination": [ "pack-resonance", 0 ] } },
      { "patchline": { "source": [ "pack-resonance", 0 ], "destination": [ "line-resonance", 0 ] } },
      { "patchline": { "source": [ "line-resonance", 0 ], "destination": [ "filter", 4 ] } },

      { "patchline": { "source": [ "filter", 0 ], "destination": [ "clean-comp", 0 ] } },
      { "patchline": { "source": [ "filter", 1 ], "destination": [ "clean-comp", 1 ] } },
      { "patchline": { "source": [ "filter", 0 ], "destination": [ "omx-comp", 0 ] } },
      { "patchline": { "source": [ "filter", 1 ], "destination": [ "omx-comp", 1 ] } },
      { "patchline": { "source": [ "filter", 0 ], "destination": [ "dry-l", 0 ] } },
      { "patchline": { "source": [ "filter", 1 ], "destination": [ "dry-r", 0 ] } },
      { "patchline": { "source": [ "omx-loadbang", 0 ], "destination": [ "omx-init", 0 ] } },
      { "patchline": { "source": [ "omx-init", 0 ], "destination": [ "omx-comp", 0 ] } },

      { "patchline": { "source": [ "r-engine", 0 ], "destination": [ "clip-engine", 0 ] } },
      { "patchline": { "source": [ "load-engine", 0 ], "destination": [ "clip-engine", 0 ] } },
      { "patchline": { "source": [ "clip-engine", 0 ], "destination": [ "trigger-engine", 0 ] } },
      { "patchline": { "source": [ "trigger-engine", 1 ], "destination": [ "engine-mix", 0 ] } },
      { "patchline": { "source": [ "r-mix", 0 ], "destination": [ "clip-mix", 0 ] } },
      { "patchline": { "source": [ "load-mix", 0 ], "destination": [ "clip-mix", 0 ] } },
      { "patchline": { "source": [ "clip-mix", 0 ], "destination": [ "trigger-mix", 0 ] } },
      { "patchline": { "source": [ "trigger-mix", 1 ], "destination": [ "engine-mix", 1 ] } },
      { "patchline": { "source": [ "engine-mix", 0 ], "destination": [ "expr-dry", 0 ] } },
      { "patchline": { "source": [ "engine-mix", 0 ], "destination": [ "expr-clean", 0 ] } },
      { "patchline": { "source": [ "engine-mix", 0 ], "destination": [ "expr-omx", 0 ] } },
      { "patchline": { "source": [ "expr-dry", 0 ], "destination": [ "pack-dry", 0 ] } },
      { "patchline": { "source": [ "expr-clean", 0 ], "destination": [ "pack-clean-weight", 0 ] } },
      { "patchline": { "source": [ "expr-omx", 0 ], "destination": [ "pack-omx-weight", 0 ] } },
      { "patchline": { "source": [ "pack-dry", 0 ], "destination": [ "line-dry", 0 ] } },
      { "patchline": { "source": [ "pack-clean-weight", 0 ], "destination": [ "line-clean-weight", 0 ] } },
      { "patchline": { "source": [ "pack-omx-weight", 0 ], "destination": [ "line-omx-weight", 0 ] } },
      { "patchline": { "source": [ "line-dry", 0 ], "destination": [ "dry-l", 1 ] } },
      { "patchline": { "source": [ "line-dry", 0 ], "destination": [ "dry-r", 1 ] } },

      { "patchline": { "source": [ "r-threshold", 0 ], "destination": [ "clip-threshold", 0 ] } },
      { "patchline": { "source": [ "load-threshold", 0 ], "destination": [ "clip-threshold", 0 ] } },
      { "patchline": { "source": [ "clip-threshold", 0 ], "destination": [ "trigger-threshold", 0 ] } },
      { "patchline": { "source": [ "trigger-threshold", 2 ], "destination": [ "clean-comp", 2 ] } },
      { "patchline": { "source": [ "trigger-threshold", 1 ], "destination": [ "abs-threshold", 0 ] } },
      { "patchline": { "source": [ "abs-threshold", 0 ], "destination": [ "pre-omx-threshold", 0 ] } },
      { "patchline": { "source": [ "pre-omx-threshold", 0 ], "destination": [ "omx-comp", 0 ] } },
      { "patchline": { "source": [ "r-ratio", 0 ], "destination": [ "clip-ratio", 0 ] } },
      { "patchline": { "source": [ "load-ratio", 0 ], "destination": [ "clip-ratio", 0 ] } },
      { "patchline": { "source": [ "clip-ratio", 0 ], "destination": [ "trigger-ratio", 0 ] } },
      { "patchline": { "source": [ "trigger-ratio", 2 ], "destination": [ "clean-comp", 3 ] } },
      { "patchline": { "source": [ "trigger-ratio", 1 ], "destination": [ "int-ratio", 0 ] } },
      { "patchline": { "source": [ "int-ratio", 0 ], "destination": [ "pre-omx-ratio", 0 ] } },
      { "patchline": { "source": [ "pre-omx-ratio", 0 ], "destination": [ "omx-comp", 0 ] } },
      { "patchline": { "source": [ "r-attack", 0 ], "destination": [ "clip-attack", 0 ] } },
      { "patchline": { "source": [ "load-attack", 0 ], "destination": [ "clip-attack", 0 ] } },
      { "patchline": { "source": [ "clip-attack", 0 ], "destination": [ "trigger-attack", 0 ] } },
      { "patchline": { "source": [ "trigger-attack", 2 ], "destination": [ "clean-comp", 4 ] } },
      { "patchline": { "source": [ "trigger-attack", 1 ], "destination": [ "map-omx-attack", 0 ] } },
      { "patchline": { "source": [ "map-omx-attack", 0 ], "destination": [ "pre-omx-attack", 0 ] } },
      { "patchline": { "source": [ "pre-omx-attack", 0 ], "destination": [ "omx-comp", 0 ] } },
      { "patchline": { "source": [ "r-release", 0 ], "destination": [ "clip-release", 0 ] } },
      { "patchline": { "source": [ "load-release", 0 ], "destination": [ "clip-release", 0 ] } },
      { "patchline": { "source": [ "clip-release", 0 ], "destination": [ "trigger-release", 0 ] } },
      { "patchline": { "source": [ "trigger-release", 2 ], "destination": [ "clean-comp", 5 ] } },
      { "patchline": { "source": [ "trigger-release", 1 ], "destination": [ "map-omx-release", 0 ] } },
      { "patchline": { "source": [ "map-omx-release", 0 ], "destination": [ "pre-omx-release", 0 ] } },
      { "patchline": { "source": [ "pre-omx-release", 0 ], "destination": [ "omx-comp", 0 ] } },
      { "patchline": { "source": [ "r-knee", 0 ], "destination": [ "clip-knee", 0 ] } },
      { "patchline": { "source": [ "load-knee", 0 ], "destination": [ "clip-knee", 0 ] } },
      { "patchline": { "source": [ "clip-knee", 0 ], "destination": [ "trigger-knee", 0 ] } },
      { "patchline": { "source": [ "trigger-knee", 1 ], "destination": [ "clean-comp", 6 ] } },
      { "patchline": { "source": [ "r-makeup", 0 ], "destination": [ "clip-makeup", 0 ] } },
      { "patchline": { "source": [ "load-makeup", 0 ], "destination": [ "clip-makeup", 0 ] } },
      { "patchline": { "source": [ "clip-makeup", 0 ], "destination": [ "trigger-makeup", 0 ] } },
      { "patchline": { "source": [ "trigger-makeup", 2 ], "destination": [ "makeup-scalar", 0 ] } },
      { "patchline": { "source": [ "makeup-scalar", 0 ], "destination": [ "pack-makeup", 0 ] } },
      { "patchline": { "source": [ "pack-makeup", 0 ], "destination": [ "line-makeup", 0 ] } },

      { "patchline": { "source": [ "clean-comp", 0 ], "destination": [ "clean-makeup-l", 0 ] } },
      { "patchline": { "source": [ "clean-comp", 1 ], "destination": [ "clean-makeup-r", 0 ] } },
      { "patchline": { "source": [ "line-makeup", 0 ], "destination": [ "clean-makeup-l", 1 ] } },
      { "patchline": { "source": [ "line-makeup", 0 ], "destination": [ "clean-makeup-r", 1 ] } },
      { "patchline": { "source": [ "clean-makeup-l", 0 ], "destination": [ "clean-weight-l", 0 ] } },
      { "patchline": { "source": [ "clean-makeup-r", 0 ], "destination": [ "clean-weight-r", 0 ] } },
      { "patchline": { "source": [ "line-clean-weight", 0 ], "destination": [ "clean-weight-l", 1 ] } },
      { "patchline": { "source": [ "line-clean-weight", 0 ], "destination": [ "clean-weight-r", 1 ] } },
      { "patchline": { "source": [ "omx-comp", 0 ], "destination": [ "omx-makeup-l", 0 ] } },
      { "patchline": { "source": [ "omx-comp", 1 ], "destination": [ "omx-makeup-r", 0 ] } },
      { "patchline": { "source": [ "line-makeup", 0 ], "destination": [ "omx-makeup-l", 1 ] } },
      { "patchline": { "source": [ "line-makeup", 0 ], "destination": [ "omx-makeup-r", 1 ] } },
      { "patchline": { "source": [ "omx-makeup-l", 0 ], "destination": [ "omx-weight-l", 0 ] } },
      { "patchline": { "source": [ "omx-makeup-r", 0 ], "destination": [ "omx-weight-r", 0 ] } },
      { "patchline": { "source": [ "line-omx-weight", 0 ], "destination": [ "omx-weight-l", 1 ] } },
      { "patchline": { "source": [ "line-omx-weight", 0 ], "destination": [ "omx-weight-r", 1 ] } },
      { "patchline": { "source": [ "dry-l", 0 ], "destination": [ "sum-a-l", 0 ] } },
      { "patchline": { "source": [ "clean-weight-l", 0 ], "destination": [ "sum-a-l", 1 ] } },
      { "patchline": { "source": [ "dry-r", 0 ], "destination": [ "sum-a-r", 0 ] } },
      { "patchline": { "source": [ "clean-weight-r", 0 ], "destination": [ "sum-a-r", 1 ] } },
      { "patchline": { "source": [ "sum-a-l", 0 ], "destination": [ "sum-b-l", 0 ] } },
      { "patchline": { "source": [ "omx-weight-l", 0 ], "destination": [ "sum-b-l", 1 ] } },
      { "patchline": { "source": [ "sum-a-r", 0 ], "destination": [ "sum-b-r", 0 ] } },
      { "patchline": { "source": [ "omx-weight-r", 0 ], "destination": [ "sum-b-r", 1 ] } },
      { "patchline": { "source": [ "sum-b-l", 0 ], "destination": [ "saturator", 0 ] } },
      { "patchline": { "source": [ "sum-b-r", 0 ], "destination": [ "saturator", 1 ] } },
      { "patchline": { "source": [ "r-drive", 0 ], "destination": [ "clip-drive", 0 ] } },
      { "patchline": { "source": [ "load-drive", 0 ], "destination": [ "clip-drive", 0 ] } },
      { "patchline": { "source": [ "clip-drive", 0 ], "destination": [ "trigger-drive", 0 ] } },
      { "patchline": { "source": [ "trigger-drive", 1 ], "destination": [ "saturator", 2 ] } },
      { "patchline": { "source": [ "saturator", 0 ], "destination": [ "trim-l", 0 ] } },
      { "patchline": { "source": [ "saturator", 1 ], "destination": [ "trim-r", 0 ] } },
      { "patchline": { "source": [ "r-trim", 0 ], "destination": [ "clip-trim", 0 ] } },
      { "patchline": { "source": [ "load-trim", 0 ], "destination": [ "clip-trim", 0 ] } },
      { "patchline": { "source": [ "clip-trim", 0 ], "destination": [ "trigger-trim", 0 ] } },
      { "patchline": { "source": [ "trigger-trim", 1 ], "destination": [ "trim-scalar", 0 ] } },
      { "patchline": { "source": [ "trim-scalar", 0 ], "destination": [ "pack-trim", 0 ] } },
      { "patchline": { "source": [ "pack-trim", 0 ], "destination": [ "line-trim", 0 ] } },
      { "patchline": { "source": [ "line-trim", 0 ], "destination": [ "trim-l", 1 ] } },
      { "patchline": { "source": [ "line-trim", 0 ], "destination": [ "trim-r", 1 ] } },
      { "patchline": { "source": [ "trim-l", 0 ], "destination": [ "out-l", 0 ] } },
      { "patchline": { "source": [ "trim-r", 0 ], "destination": [ "out-r", 0 ] } },

      { "patchline": { "source": [ "state-channel-load", 0 ], "destination": [ "state-channel-index", 0 ] } },
      { "patchline": { "source": [ "state-channel-index", 0 ], "destination": [ "state-pak", 0 ] } },
      { "patchline": { "source": [ "state-channel-index", 0 ], "destination": [ "meter-pak", 0 ] } },
      { "patchline": { "source": [ "trigger-engine", 0 ], "destination": [ "state-pak", 1 ] } },
      { "patchline": { "source": [ "trigger-cutoff", 1 ], "destination": [ "state-pak", 2 ] } },
      { "patchline": { "source": [ "unpack-filtermod", 0 ], "destination": [ "state-pak", 3 ] } },
      { "patchline": { "source": [ "trigger-resonance", 1 ], "destination": [ "state-pak", 4 ] } },
      { "patchline": { "source": [ "trigger-threshold", 0 ], "destination": [ "state-pak", 5 ] } },
      { "patchline": { "source": [ "trigger-ratio", 0 ], "destination": [ "state-pak", 6 ] } },
      { "patchline": { "source": [ "trigger-attack", 0 ], "destination": [ "state-pak", 7 ] } },
      { "patchline": { "source": [ "trigger-release", 0 ], "destination": [ "state-pak", 8 ] } },
      { "patchline": { "source": [ "trigger-knee", 0 ], "destination": [ "state-pak", 9 ] } },
      { "patchline": { "source": [ "trigger-makeup", 0 ], "destination": [ "state-pak", 10 ] } },
      { "patchline": { "source": [ "trigger-mix", 0 ], "destination": [ "state-pak", 11 ] } },
      { "patchline": { "source": [ "trigger-drive", 0 ], "destination": [ "state-pak", 12 ] } },
      { "patchline": { "source": [ "trigger-trim", 0 ], "destination": [ "state-pak", 13 ] } },
      { "patchline": { "source": [ "state-pak", 0 ], "destination": [ "state-speedlim", 0 ] } },
      { "patchline": { "source": [ "state-speedlim", 0 ], "destination": [ "state-prepend", 0 ] } },
      { "patchline": { "source": [ "state-prepend", 0 ], "destination": [ "hud-state-send", 0 ] } },
      { "patchline": { "source": [ "r-snapshot", 0 ], "destination": [ "snapshot-channel", 0 ] } },
      { "patchline": { "source": [ "snapshot-channel", 0 ], "destination": [ "state-channel-index", 0 ] } },

      { "patchline": { "source": [ "filter", 0 ], "destination": [ "input-abs-l", 0 ] } },
      { "patchline": { "source": [ "filter", 1 ], "destination": [ "input-abs-r", 0 ] } },
      { "patchline": { "source": [ "input-abs-l", 0 ], "destination": [ "input-max", 0 ] } },
      { "patchline": { "source": [ "input-abs-r", 0 ], "destination": [ "input-max", 1 ] } },
      { "patchline": { "source": [ "input-max", 0 ], "destination": [ "input-peak", 0 ] } },
      { "patchline": { "source": [ "input-peak", 0 ], "destination": [ "input-db", 0 ] } },
      { "patchline": { "source": [ "input-db", 0 ], "destination": [ "meter-pak", 1 ] } },
      { "patchline": { "source": [ "trim-l", 0 ], "destination": [ "output-abs-l", 0 ] } },
      { "patchline": { "source": [ "trim-r", 0 ], "destination": [ "output-abs-r", 0 ] } },
      { "patchline": { "source": [ "output-abs-l", 0 ], "destination": [ "output-max", 0 ] } },
      { "patchline": { "source": [ "output-abs-r", 0 ], "destination": [ "output-max", 1 ] } },
      { "patchline": { "source": [ "output-max", 0 ], "destination": [ "output-peak", 0 ] } },
      { "patchline": { "source": [ "output-peak", 0 ], "destination": [ "output-db", 0 ] } },
      { "patchline": { "source": [ "output-db", 0 ], "destination": [ "meter-pak", 2 ] } },
      { "patchline": { "source": [ "trigger-makeup", 0 ], "destination": [ "meter-pak", 3 ] } },
      { "patchline": { "source": [ "r-meter-selected", 0 ], "destination": [ "meter-equals", 0 ] } },
      { "patchline": { "source": [ "meter-equals", 0 ], "destination": [ "meter-metro", 0 ] } },
      { "patchline": { "source": [ "meter-metro", 0 ], "destination": [ "meter-trigger", 0 ] } },
      { "patchline": { "source": [ "meter-trigger", 1 ], "destination": [ "output-peak", 0 ] } },
      { "patchline": { "source": [ "meter-trigger", 0 ], "destination": [ "input-peak", 0 ] } },
      { "patchline": { "source": [ "meter-pak", 0 ], "destination": [ "meter-speedlim", 0 ] } },
      { "patchline": { "source": [ "meter-speedlim", 0 ], "destination": [ "meter-prepend", 0 ] } },
      { "patchline": { "source": [ "meter-prepend", 0 ], "destination": [ "meter-send", 0 ] } }
    ]
  }
}
