{
  "patcher": {
    "fileversion": 1,
    "appversion": { "major": 9, "minor": 1, "revision": 5, "architecture": "arm64", "modernui": 1 },
    "classnamespace": "box",
    "rect": [ 50.0, 80.0, 920.0, 520.0 ],
    "openinpresentation": 0,
    "boxes": [
      { "box": { "id": "obj-command", "maxclass": "newobj", "text": "r mlr_session_cmd", "patching_rect": [ 24.0, 24.0, 128.0, 22.0 ], "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ] } },
      { "box": { "id": "obj-dirty", "maxclass": "newobj", "text": "r mlr_session_dirty", "patching_rect": [ 170.0, 24.0, 140.0, 22.0 ], "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ] } },
      { "box": { "id": "obj-fragment", "maxclass": "newobj", "text": "r mlr_session_fragment", "patching_rect": [ 328.0, 24.0, 155.0, 22.0 ], "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ] } },
      { "box": { "id": "obj-hud", "maxclass": "newobj", "text": "r mlr_hud_state", "patching_rect": [ 500.0, 24.0, 115.0, 22.0 ], "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ] } },
      { "box": { "id": "obj-hud-prefix", "maxclass": "newobj", "text": "prepend state", "patching_rect": [ 500.0, 61.0, 95.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ] } },
      { "box": { "id": "obj-rec-state", "maxclass": "newobj", "text": "r mlr_session_recording_state", "patching_rect": [ 634.0, 24.0, 190.0, 22.0 ], "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ] } },
      { "box": { "id": "obj-rec-prefix", "maxclass": "newobj", "text": "prepend recording_state", "patching_rect": [ 634.0, 61.0, 155.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ] } },
      { "box": { "id": "obj-rec-status", "maxclass": "newobj", "text": "r mlr_session_recording_status", "patching_rect": [ 634.0, 98.0, 195.0, 22.0 ], "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ] } },
      { "box": { "id": "obj-bridge", "maxclass": "newobj", "text": "v8 mlr_session_bridge.js @autowatch 1", "patching_rect": [ 255.0, 151.0, 245.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "" ] } },
      { "box": { "id": "obj-node", "maxclass": "newobj", "text": "node.script mlr_session_manager.js @autostart 1", "patching_rect": [ 255.0, 216.0, 290.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "" ] } },
      { "box": { "id": "obj-node-command", "maxclass": "newobj", "text": "r mlr_session_node_cmd", "patching_rect": [ 24.0, 216.0, 165.0, 22.0 ], "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ] } },
      { "box": { "id": "obj-dialog-route", "maxclass": "newobj", "text": "route save_dialog open_dialog relink_dialog", "patching_rect": [ 570.0, 151.0, 270.0, 22.0 ], "numinlets": 1, "numoutlets": 4, "outlettype": [ "", "", "", "" ] } },
      { "box": { "id": "obj-save-dialog", "maxclass": "newobj", "text": "savedialog", "patching_rect": [ 570.0, 216.0, 75.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ] } },
      { "box": { "id": "obj-open-dialog", "maxclass": "newobj", "text": "opendialog fold", "patching_rect": [ 665.0, 216.0, 105.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ] } },
      { "box": { "id": "obj-relink-dialog", "maxclass": "newobj", "text": "opendialog fold", "patching_rect": [ 790.0, 216.0, 105.0, 22.0 ], "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ] } },
      { "box": { "id": "obj-save-path", "maxclass": "newobj", "text": "prepend save_path", "patching_rect": [ 570.0, 266.0, 115.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ] } },
      { "box": { "id": "obj-open-path", "maxclass": "newobj", "text": "prepend open_path", "patching_rect": [ 697.0, 266.0, 115.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ] } },
      { "box": { "id": "obj-relink-path", "maxclass": "newobj", "text": "prepend relink_path", "patching_rect": [ 824.0, 266.0, 125.0, 22.0 ], "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ] } },
      { "box": { "id": "obj-export", "maxclass": "newobj", "text": "mlr_recording_export", "patching_rect": [ 24.0, 320.0, 145.0, 22.0 ], "numinlets": 0, "numoutlets": 0 } },
      { "box": { "id": "obj-note", "maxclass": "comment", "text": "Central transaction owner: snapshots Max state, delegates filesystem work to Node, and applies only preflighted bundles.", "patching_rect": [ 255.0, 330.0, 620.0, 20.0 ] } }
    ],
    "lines": [
      { "patchline": { "source": [ "obj-command", 0 ], "destination": [ "obj-bridge", 0 ] } },
      { "patchline": { "source": [ "obj-dirty", 0 ], "destination": [ "obj-bridge", 0 ] } },
      { "patchline": { "source": [ "obj-fragment", 0 ], "destination": [ "obj-bridge", 0 ] } },
      { "patchline": { "source": [ "obj-hud", 0 ], "destination": [ "obj-hud-prefix", 0 ] } },
      { "patchline": { "source": [ "obj-hud-prefix", 0 ], "destination": [ "obj-bridge", 0 ] } },
      { "patchline": { "source": [ "obj-rec-state", 0 ], "destination": [ "obj-rec-prefix", 0 ] } },
      { "patchline": { "source": [ "obj-rec-prefix", 0 ], "destination": [ "obj-bridge", 0 ] } },
      { "patchline": { "source": [ "obj-rec-status", 0 ], "destination": [ "obj-bridge", 0 ] } },
      { "patchline": { "source": [ "obj-bridge", 0 ], "destination": [ "obj-node", 0 ] } },
      { "patchline": { "source": [ "obj-node", 0 ], "destination": [ "obj-bridge", 0 ] } },
      { "patchline": { "source": [ "obj-node-command", 0 ], "destination": [ "obj-node", 0 ] } },
      { "patchline": { "source": [ "obj-bridge", 1 ], "destination": [ "obj-dialog-route", 0 ] } },
      { "patchline": { "source": [ "obj-dialog-route", 0 ], "destination": [ "obj-save-dialog", 0 ] } },
      { "patchline": { "source": [ "obj-dialog-route", 1 ], "destination": [ "obj-open-dialog", 0 ] } },
      { "patchline": { "source": [ "obj-dialog-route", 2 ], "destination": [ "obj-relink-dialog", 0 ] } },
      { "patchline": { "source": [ "obj-save-dialog", 0 ], "destination": [ "obj-save-path", 0 ] } },
      { "patchline": { "source": [ "obj-open-dialog", 0 ], "destination": [ "obj-open-path", 0 ] } },
      { "patchline": { "source": [ "obj-relink-dialog", 0 ], "destination": [ "obj-relink-path", 0 ] } },
      { "patchline": { "source": [ "obj-save-path", 0 ], "destination": [ "obj-bridge", 0 ] } },
      { "patchline": { "source": [ "obj-open-path", 0 ], "destination": [ "obj-bridge", 0 ] } },
      { "patchline": { "source": [ "obj-relink-path", 0 ], "destination": [ "obj-bridge", 0 ] } }
    ]
  }
}
