{
  "patcher": {
    "fileversion": 1,
    "appversion": {
      "major": 9,
      "minor": 1,
      "revision": 3,
      "architecture": "x64",
      "modernui": 1
    },
    "classnamespace": "box",
    "rect": [80.0, 80.0, 1180.0, 650.0],
    "boxes": [
      { "box": { "id": "obj-title", "maxclass": "comment", "text": "ṛta native audio bridge — V8 arms one cut per group; the next audio-derived sequence64 pulse releases it without passing through JavaScript.", "patching_rect": [30.0, 20.0, 850.0, 22.0] } },
      { "box": { "id": "obj-rarm", "maxclass": "newobj", "text": "r sequence64_audio_arm", "numinlets": 0, "numoutlets": 1, "outlettype": [""], "patching_rect": [30.0, 70.0, 142.0, 22.0] } },
      { "box": { "id": "obj-routearm", "maxclass": "newobj", "text": "route 1 2 3 4 5 6 7 8", "numinlets": 1, "numoutlets": 9, "outlettype": ["", "", "", "", "", "", "", "", ""], "patching_rect": [30.0, 110.0, 202.0, 22.0] } },
      { "box": { "id": "obj-reg1", "maxclass": "newobj", "text": "zl reg", "numinlets": 2, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [30.0, 185.0, 48.0, 22.0] } },
      { "box": { "id": "obj-reg2", "maxclass": "newobj", "text": "zl reg", "numinlets": 2, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [110.0, 185.0, 48.0, 22.0] } },
      { "box": { "id": "obj-reg3", "maxclass": "newobj", "text": "zl reg", "numinlets": 2, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [190.0, 185.0, 48.0, 22.0] } },
      { "box": { "id": "obj-reg4", "maxclass": "newobj", "text": "zl reg", "numinlets": 2, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [270.0, 185.0, 48.0, 22.0] } },
      { "box": { "id": "obj-reg5", "maxclass": "newobj", "text": "zl reg", "numinlets": 2, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [350.0, 185.0, 48.0, 22.0] } },
      { "box": { "id": "obj-reg6", "maxclass": "newobj", "text": "zl reg", "numinlets": 2, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [430.0, 185.0, 48.0, 22.0] } },
      { "box": { "id": "obj-reg7", "maxclass": "newobj", "text": "zl reg", "numinlets": 2, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [510.0, 185.0, 48.0, 22.0] } },
      { "box": { "id": "obj-reg8", "maxclass": "newobj", "text": "zl reg", "numinlets": 2, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [590.0, 185.0, 48.0, 22.0] } },
      { "box": { "id": "obj-pre1", "maxclass": "newobj", "text": "prepend 1", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [30.0, 235.0, 65.0, 22.0] } },
      { "box": { "id": "obj-pre2", "maxclass": "newobj", "text": "prepend 2", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [110.0, 235.0, 65.0, 22.0] } },
      { "box": { "id": "obj-pre3", "maxclass": "newobj", "text": "prepend 3", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [190.0, 235.0, 65.0, 22.0] } },
      { "box": { "id": "obj-pre4", "maxclass": "newobj", "text": "prepend 4", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [270.0, 235.0, 65.0, 22.0] } },
      { "box": { "id": "obj-pre5", "maxclass": "newobj", "text": "prepend 5", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [350.0, 235.0, 65.0, 22.0] } },
      { "box": { "id": "obj-pre6", "maxclass": "newobj", "text": "prepend 6", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [430.0, 235.0, 65.0, 22.0] } },
      { "box": { "id": "obj-pre7", "maxclass": "newobj", "text": "prepend 7", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [510.0, 235.0, 65.0, 22.0] } },
      { "box": { "id": "obj-pre8", "maxclass": "newobj", "text": "prepend 8", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [590.0, 235.0, 65.0, 22.0] } },
      { "box": { "id": "obj-rpulse", "maxclass": "newobj", "text": "r sequence64_pulse", "numinlets": 0, "numoutlets": 1, "outlettype": [""], "patching_rect": [720.0, 70.0, 118.0, 22.0] } },
      { "box": { "id": "obj-pulsetrigger", "maxclass": "newobj", "text": "t b b", "numinlets": 1, "numoutlets": 2, "outlettype": ["bang", "bang"], "patching_rect": [720.0, 110.0, 42.0, 22.0] } },
      { "box": { "id": "obj-clearall", "maxclass": "message", "text": "zlclear", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [775.0, 150.0, 47.0, 22.0] } },
      { "box": { "id": "obj-loadbang", "maxclass": "newobj", "text": "loadbang", "numinlets": 1, "numoutlets": 1, "outlettype": ["bang"], "patching_rect": [850.0, 110.0, 60.0, 22.0] } },
      { "box": { "id": "obj-rcancel", "maxclass": "newobj", "text": "r sequence64_audio_cancel", "numinlets": 0, "numoutlets": 1, "outlettype": [""], "patching_rect": [30.0, 315.0, 155.0, 22.0] } },
      { "box": { "id": "obj-routecancel", "maxclass": "newobj", "text": "route 1 2 3 4 5 6 7 8", "numinlets": 1, "numoutlets": 9, "outlettype": ["", "", "", "", "", "", "", "", ""], "patching_rect": [30.0, 355.0, 202.0, 22.0] } },
      { "box": { "id": "obj-clear1", "maxclass": "message", "text": "zlclear", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [30.0, 395.0, 47.0, 22.0] } },
      { "box": { "id": "obj-clear2", "maxclass": "message", "text": "zlclear", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [90.0, 395.0, 47.0, 22.0] } },
      { "box": { "id": "obj-clear3", "maxclass": "message", "text": "zlclear", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [150.0, 395.0, 47.0, 22.0] } },
      { "box": { "id": "obj-clear4", "maxclass": "message", "text": "zlclear", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [210.0, 395.0, 47.0, 22.0] } },
      { "box": { "id": "obj-clear5", "maxclass": "message", "text": "zlclear", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [270.0, 395.0, 47.0, 22.0] } },
      { "box": { "id": "obj-clear6", "maxclass": "message", "text": "zlclear", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [330.0, 395.0, 47.0, 22.0] } },
      { "box": { "id": "obj-clear7", "maxclass": "message", "text": "zlclear", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [390.0, 395.0, 47.0, 22.0] } },
      { "box": { "id": "obj-clear8", "maxclass": "message", "text": "zlclear", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [450.0, 395.0, 47.0, 22.0] } },
      { "box": { "id": "obj-actiontrigger", "maxclass": "newobj", "text": "t l l l", "numinlets": 1, "numoutlets": 3, "outlettype": ["list", "list", "list"], "patching_rect": [690.0, 285.0, 55.0, 22.0] } },
      { "box": { "id": "obj-nthtrack", "maxclass": "newobj", "text": "zl nth 2", "numinlets": 2, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [900.0, 330.0, 60.0, 22.0] } },
      { "box": { "id": "obj-trackname", "maxclass": "newobj", "text": "sprintf %ldinput", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [900.0, 370.0, 102.0, 22.0] } },
      { "box": { "id": "obj-tracksend", "maxclass": "newobj", "text": "prepend send", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [900.0, 410.0, 84.0, 22.0] } },
      { "box": { "id": "obj-nthchannel", "maxclass": "newobj", "text": "zl nth 1", "numinlets": 2, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [775.0, 330.0, 60.0, 22.0] } },
      { "box": { "id": "obj-channelname", "maxclass": "newobj", "text": "sprintf %ld[mlr]pl-trig-now", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [775.0, 370.0, 174.0, 22.0] } },
      { "box": { "id": "obj-channelsend", "maxclass": "newobj", "text": "prepend send", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [790.0, 410.0, 84.0, 22.0] } },
      { "box": { "id": "obj-nthslice", "maxclass": "newobj", "text": "zl nth 3", "numinlets": 2, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [650.0, 330.0, 60.0, 22.0] } },
      { "box": { "id": "obj-fireorder", "maxclass": "newobj", "text": "t i b i", "numinlets": 1, "numoutlets": 3, "outlettype": ["int", "bang", "int"], "patching_rect": [650.0, 450.0, 52.0, 22.0] } },
      { "box": { "id": "obj-press", "maxclass": "message", "text": "$1 1", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [720.0, 495.0, 38.0, 22.0] } },
      { "box": { "id": "obj-release", "maxclass": "message", "text": "$1 0", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [610.0, 495.0, 38.0, 22.0] } },
      { "box": { "id": "obj-forwardtrack", "maxclass": "newobj", "text": "forward", "numinlets": 1, "numoutlets": 0, "patching_rect": [680.0, 550.0, 55.0, 22.0] } },
      { "box": { "id": "obj-forwardtrigger", "maxclass": "newobj", "text": "forward", "numinlets": 1, "numoutlets": 0, "patching_rect": [790.0, 550.0, 55.0, 22.0] } }
    ],
    "lines": [
      { "patchline": { "source": ["obj-rarm", 0], "destination": ["obj-routearm", 0] } },
      { "patchline": { "source": ["obj-routearm", 0], "destination": ["obj-reg1", 1] } },
      { "patchline": { "source": ["obj-routearm", 1], "destination": ["obj-reg2", 1] } },
      { "patchline": { "source": ["obj-routearm", 2], "destination": ["obj-reg3", 1] } },
      { "patchline": { "source": ["obj-routearm", 3], "destination": ["obj-reg4", 1] } },
      { "patchline": { "source": ["obj-routearm", 4], "destination": ["obj-reg5", 1] } },
      { "patchline": { "source": ["obj-routearm", 5], "destination": ["obj-reg6", 1] } },
      { "patchline": { "source": ["obj-routearm", 6], "destination": ["obj-reg7", 1] } },
      { "patchline": { "source": ["obj-routearm", 7], "destination": ["obj-reg8", 1] } },
      { "patchline": { "source": ["obj-rpulse", 0], "destination": ["obj-pulsetrigger", 0] } },
      { "patchline": { "source": ["obj-pulsetrigger", 1], "destination": ["obj-reg1", 0] } },
      { "patchline": { "source": ["obj-pulsetrigger", 1], "destination": ["obj-reg2", 0] } },
      { "patchline": { "source": ["obj-pulsetrigger", 1], "destination": ["obj-reg3", 0] } },
      { "patchline": { "source": ["obj-pulsetrigger", 1], "destination": ["obj-reg4", 0] } },
      { "patchline": { "source": ["obj-pulsetrigger", 1], "destination": ["obj-reg5", 0] } },
      { "patchline": { "source": ["obj-pulsetrigger", 1], "destination": ["obj-reg6", 0] } },
      { "patchline": { "source": ["obj-pulsetrigger", 1], "destination": ["obj-reg7", 0] } },
      { "patchline": { "source": ["obj-pulsetrigger", 1], "destination": ["obj-reg8", 0] } },
      { "patchline": { "source": ["obj-pulsetrigger", 0], "destination": ["obj-clearall", 0] } },
      { "patchline": { "source": ["obj-loadbang", 0], "destination": ["obj-clearall", 0] } },
      { "patchline": { "source": ["obj-clearall", 0], "destination": ["obj-reg1", 0] } },
      { "patchline": { "source": ["obj-clearall", 0], "destination": ["obj-reg2", 0] } },
      { "patchline": { "source": ["obj-clearall", 0], "destination": ["obj-reg3", 0] } },
      { "patchline": { "source": ["obj-clearall", 0], "destination": ["obj-reg4", 0] } },
      { "patchline": { "source": ["obj-clearall", 0], "destination": ["obj-reg5", 0] } },
      { "patchline": { "source": ["obj-clearall", 0], "destination": ["obj-reg6", 0] } },
      { "patchline": { "source": ["obj-clearall", 0], "destination": ["obj-reg7", 0] } },
      { "patchline": { "source": ["obj-clearall", 0], "destination": ["obj-reg8", 0] } },
      { "patchline": { "source": ["obj-reg1", 0], "destination": ["obj-pre1", 0] } },
      { "patchline": { "source": ["obj-reg2", 0], "destination": ["obj-pre2", 0] } },
      { "patchline": { "source": ["obj-reg3", 0], "destination": ["obj-pre3", 0] } },
      { "patchline": { "source": ["obj-reg4", 0], "destination": ["obj-pre4", 0] } },
      { "patchline": { "source": ["obj-reg5", 0], "destination": ["obj-pre5", 0] } },
      { "patchline": { "source": ["obj-reg6", 0], "destination": ["obj-pre6", 0] } },
      { "patchline": { "source": ["obj-reg7", 0], "destination": ["obj-pre7", 0] } },
      { "patchline": { "source": ["obj-reg8", 0], "destination": ["obj-pre8", 0] } },
      { "patchline": { "source": ["obj-pre1", 0], "destination": ["obj-actiontrigger", 0] } },
      { "patchline": { "source": ["obj-pre2", 0], "destination": ["obj-actiontrigger", 0] } },
      { "patchline": { "source": ["obj-pre3", 0], "destination": ["obj-actiontrigger", 0] } },
      { "patchline": { "source": ["obj-pre4", 0], "destination": ["obj-actiontrigger", 0] } },
      { "patchline": { "source": ["obj-pre5", 0], "destination": ["obj-actiontrigger", 0] } },
      { "patchline": { "source": ["obj-pre6", 0], "destination": ["obj-actiontrigger", 0] } },
      { "patchline": { "source": ["obj-pre7", 0], "destination": ["obj-actiontrigger", 0] } },
      { "patchline": { "source": ["obj-pre8", 0], "destination": ["obj-actiontrigger", 0] } },
      { "patchline": { "source": ["obj-actiontrigger", 2], "destination": ["obj-nthtrack", 0] } },
      { "patchline": { "source": ["obj-nthtrack", 0], "destination": ["obj-trackname", 0] } },
      { "patchline": { "source": ["obj-trackname", 0], "destination": ["obj-tracksend", 0] } },
      { "patchline": { "source": ["obj-tracksend", 0], "destination": ["obj-forwardtrack", 0] } },
      { "patchline": { "source": ["obj-actiontrigger", 1], "destination": ["obj-nthchannel", 0] } },
      { "patchline": { "source": ["obj-nthchannel", 0], "destination": ["obj-channelname", 0] } },
      { "patchline": { "source": ["obj-channelname", 0], "destination": ["obj-channelsend", 0] } },
      { "patchline": { "source": ["obj-channelsend", 0], "destination": ["obj-forwardtrigger", 0] } },
      { "patchline": { "source": ["obj-actiontrigger", 0], "destination": ["obj-nthslice", 0] } },
      { "patchline": { "source": ["obj-nthslice", 0], "destination": ["obj-fireorder", 0] } },
      { "patchline": { "source": ["obj-fireorder", 2], "destination": ["obj-press", 0] } },
      { "patchline": { "source": ["obj-press", 0], "destination": ["obj-forwardtrack", 0] } },
      { "patchline": { "source": ["obj-fireorder", 1], "destination": ["obj-forwardtrigger", 0] } },
      { "patchline": { "source": ["obj-fireorder", 0], "destination": ["obj-release", 0] } },
      { "patchline": { "source": ["obj-release", 0], "destination": ["obj-forwardtrack", 0] } },
      { "patchline": { "source": ["obj-rcancel", 0], "destination": ["obj-routecancel", 0] } },
      { "patchline": { "source": ["obj-routecancel", 0], "destination": ["obj-clear1", 0] } },
      { "patchline": { "source": ["obj-routecancel", 1], "destination": ["obj-clear2", 0] } },
      { "patchline": { "source": ["obj-routecancel", 2], "destination": ["obj-clear3", 0] } },
      { "patchline": { "source": ["obj-routecancel", 3], "destination": ["obj-clear4", 0] } },
      { "patchline": { "source": ["obj-routecancel", 4], "destination": ["obj-clear5", 0] } },
      { "patchline": { "source": ["obj-routecancel", 5], "destination": ["obj-clear6", 0] } },
      { "patchline": { "source": ["obj-routecancel", 6], "destination": ["obj-clear7", 0] } },
      { "patchline": { "source": ["obj-routecancel", 7], "destination": ["obj-clear8", 0] } },
      { "patchline": { "source": ["obj-clear1", 0], "destination": ["obj-reg1", 0] } },
      { "patchline": { "source": ["obj-clear2", 0], "destination": ["obj-reg2", 0] } },
      { "patchline": { "source": ["obj-clear3", 0], "destination": ["obj-reg3", 0] } },
      { "patchline": { "source": ["obj-clear4", 0], "destination": ["obj-reg4", 0] } },
      { "patchline": { "source": ["obj-clear5", 0], "destination": ["obj-reg5", 0] } },
      { "patchline": { "source": ["obj-clear6", 0], "destination": ["obj-reg6", 0] } },
      { "patchline": { "source": ["obj-clear7", 0], "destination": ["obj-reg7", 0] } },
      { "patchline": { "source": ["obj-clear8", 0], "destination": ["obj-reg8", 0] } }
    ]
  }
}
